### PR TITLE
Update RIOT to 2019-01

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR reworks the apps and modules to be compatible with RIOT/2019.01-branch.

Test Procedure:

Verified that all applications compile correctly. Tested basic workflow for node_empty.

### CODE REVIEW

**Comment by aabadie** [comment]
The CI on Travis is failing probably because of the toolchain version. Using the RIOT build in docker feature would certainly help.

**Comment by fjmolinas** [comment]
@aabadie do you mean adding BUILD_IN_DOCKER by default? Shouldn't the proper fix be to do this in the CI configuration file? It should use docker when compiling.

I could add to the base Makefile: BUILD_IN_DOCKER ?= 1, but I don't think is the correct approach.

**Comment by aabadie** [comment]
I meant use BUILD_IN_DOCKER in Travis CI

**Comment by fjmolinas** [comment]
@aabadie , sorry dumb misunderstanding on my side.

**Comment by fjmolinas** [comment]
@aabadie All checks are passing!

**Comment by aabadie** [comment]
Great! I'll make a last pass of review before merging.

**Pull request merged**
