### PR TITLE
Fix bmx280 temperature string formatting

### LINKED ISSUE #4: Wrong format for temperatures below zero
In coap_bme280.x  on line 47 and 96 the formatting is wrong...

As imple test with:

	int	temperature;

	for (temperature = 100; temperature > -2000; temperature = temperature - 10)
		printf("Temperature is: %d.%d\n", temperature / 100, (temperature % 100) /10);

Gives:

Temperature is: 1.0
Temperature is: 0.9
Temperature is: 0.8
Temperature is: 0.7
Temperature is: 0.6
Temperature is: 0.5
Temperature is: 0.4
Temperature is: 0.3
Temperature is: 0.2
Temperature is: 0.1
Temperature is: 0.0
Temperature is: 0.-1
Temperature is: 0.-2
Temperature is: 0.-3
Temperature is: 0.-4
Temperature is: 0.-5
Temperature is: 0.-6
Temperature is: 0.-7
Temperature is: 0.-8
Temperature is: 0.-9
Temperature is: -1.0
Temperature is: -1.-1
Temperature is: -1.-2
Temperature is: -1.-3

### PR DESCRIPTION
**Pull request by aabadie**
Fixes #4

@richardklingler, this should fix the problem with the badly formatted temperature values. Can you verify on your side ?

### CODE REVIEW

**Comment by richardklingler** [comment]
Updated a node in the garden...sure it will hit below zero soon (o;

**Comment by aabadie** [comment]
> Updated a node in the garden...

Great !
Out of curiosity: are you using these RIOT firmwares with [Pyaiot](https://github.com/pyaiot/pyaiot) ?

**Comment by richardklingler** [comment]
Not yet...seems to be complicated to install on RPi (o;

But sure will look into it more as I would like to use parts of it on a RPi with touchscreen and running kivy GUI framework on top....

**Comment by aabadie** [comment]
> seems to be complicated to install on RPi

RPI is not a requirement. You can run the services on PCs/VMs but they have to be reachable from the nodes (and vice-versa) using IPv6...

**Comment by 14mRh4X0r** [comment]
This fix will display temperatures between 0 and -1 °C incorrectly, displaying e.g. -0.4 °C as 0.4 °C.

**Comment by aabadie** [comment]
> This fix will display temperatures between 0 and -1 °C incorrectly, displaying e.g. -0.4 °C as 0.4 °C.

Arf, you are right.... I'll consider using the `fmt` module from RIOT that contains helper functions for that.

**Comment by aabadie** [comment]
Finally went for another simple solution. Simpler and which works. Merging.

**Pull request merged**
